REM INSERTING into TPPOO.PRODUIT
SET DEFINE OFF;
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('R34','tablette tactile','12','22000','1');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('E57','telephone','45','37000','1');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('Z72','smartwatch','12','7000','1');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('Z84','kids  watch','15','4500','1');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('B40','televiseurs','26','45000','2');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('B45','démodulateur','36','41000','2');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('B52','wifispeaker','88','9000','2');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('P89','soundBar','10','6000','2');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C458','Climatiseurs','13','67000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C47','cuisinière','23','37000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C473','hotte de  cuisine','20','15000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C561',' plaque de cuisson','18','12000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C762','lave linge','18','70000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C845','réfrigérateurs','7','90000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C8','aspirateur ','13','9500','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C9','ventilateur','18','5500','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C101',' congélateur ','10','25000','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('C102','chaud et froid','10','25500','3');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME241','pc bureau','21','2500','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME242','pc portable','12','60000','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME243','pc all in one','8','80000','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME230','serveur','5','70000','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME262','station de travail','5','75000','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME252','périphériques ','14','5000','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('ME250','accessoires','16','4000','4');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('L300','batteries solaires','10','30000','5');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('L500','onduleurs solaires','12','15000','5');
Insert into TPPOO.PRODUIT (REF_PRO,NOM_PRO,QUANT_PRO,PRIX_PRO,ID_CAT) values ('L200','module photovoltaïque','14','21000','5');
